---
# Specify Only One Master Server 
# It must have redis_master: True

  - hosts: master_server 
    sudo: true
    roles:
       - common
       - { role: redis, redis_port: 6379, sentinel_port: 29000, redis_master: True }

# Slave Server
  - hosts: slave_servers
    sudo: true
    roles:
       - common
       - { role: redis, redis_port: 6380, sentinel_port: 29001 }
